eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
  rabbitmq:
    host: localhost
